init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  home: C:\projects
  cmake: C:\projects\cmake-3.4.1-win32-x86\bin\cmake.exe
  matrix:
  - generator : Visual Studio 14
  - generator : Visual Studio 12
  - generator : Visual Studio 14 Win64
  - generator : Visual Studio 12 Win64

version: '{branch}-{build}'

os: Visual Studio 2015

branches:
  only:
    - master

install:
  # Clone submodule
  - git submodule update --init --recursive
  # Get a recent CMake:
  - cmd: cd %home%
  - ps: wget https://cmake.org/files/v3.4/cmake-3.4.1-win32-x86.zip -OutFile cmake.zip
  - cmd: 7z x cmake.zip -o"C:\projects" -y > nul # will extract to cmake-3.4.1-win32-x86\
  - cmd: '%cmake% --version'

# gradient-check test is too slow to execute on debug mode
configuration: Release

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: '%cmake% -G "%generator%" -DUSE_SSE=ON -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=..\install ..\tiny-dnn'

after_build:
  - cmd: 'cd C:\projects\build\test\Release'
  - cmd: tiny_dnn_test.exe

build_script:
  - msbuild C:\projects\build\tiny_dnn.sln
